### ISSUE TITLE
Problems with packages

### ISSUE THREAD

**Issue by JimenaEB** [breatheco-de/exercise-conditional-profile-card#39]
Hi!

There are so many packages deprecated in this version, and the exercise doesn't work correctly. Students can't run it.
I solved these problems ASAP to can continue with my class schedule.
You can find all the changes here https://github.com/JimenaEB/4Geeks-Academy_exercise_conditional-profile-card (it's based on our JS-Webpack boilerplate)

**Comment by mojonapower** [comment]
Thanks Jimena, i'll use your solution with students  😺

**Comment by alesanchezr** [comment]
updated to latest versions.
